# Generated by Django 2.0 on 2019-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.IntegerField(blank=True, db_column='clientID', null=True)),
                ('clientname', models.CharField(blank=True, db_column='clientName', max_length=254, null=True)),
                ('regionid', models.IntegerField(blank=True, db_column='regionId', null=True)),
                ('regionsite', models.CharField(blank=True, db_column='regionSite', max_length=254, null=True)),
                ('regionphone', models.CharField(blank=True, db_column='regionPhone', max_length=254, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityid', models.IntegerField(blank=True, db_column='commodityID', null=True)),
                ('commodityna', models.CharField(blank=True, db_column='commodityNa', max_length=254, null=True)),
                ('commodityty', models.IntegerField(blank=True, db_column='commodityTy', null=True)),
                ('typeid', models.IntegerField(blank=True, db_column='typeId', null=True)),
            ],
            options={
                'db_table': 'commodity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(blank=True, db_column='orderID', null=True)),
                ('orderdate', models.CharField(blank=True, db_column='orderDate', max_length=254, null=True)),
                ('ordergetdat', models.CharField(blank=True, db_column='orderGetDat', max_length=254, null=True)),
                ('ordermoney', models.CharField(blank=True, db_column='orderMoney', max_length=254, null=True)),
                ('clientid', models.IntegerField(blank=True, db_column='clientID', null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(blank=True, db_column='orderID', null=True)),
                ('detailid', models.IntegerField(blank=True, db_column='detailID', null=True)),
                ('commodityid', models.CharField(blank=True, db_column='commodityID', max_length=254, null=True)),
                ('detailprice', models.CharField(blank=True, db_column='detailPrice', max_length=254, null=True)),
                ('detailaccou', models.IntegerField(blank=True, db_column='detailAccou', null=True)),
            ],
            options={
                'db_table': 'orderdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionid', models.IntegerField(blank=True, db_column='regionID', null=True)),
                ('regionname', models.CharField(blank=True, db_column='regionName', max_length=254, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(blank=True, db_column='typeID', null=True)),
                ('typename', models.CharField(blank=True, db_column='typeName', max_length=254, null=True)),
                ('typestate', models.CharField(blank=True, db_column='typeState', max_length=254, null=True)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
    ]
