# Generated by Django 2.0 on 2019-06-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=12)),
                ('day', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'change_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesid', models.PositiveIntegerField(blank=True, db_column='datesId', null=True)),
                ('areaid', models.PositiveIntegerField(blank=True, db_column='areaId', null=True)),
                ('goodsid', models.PositiveIntegerField(blank=True, db_column='goodsId', null=True)),
                ('customerid', models.PositiveIntegerField(blank=True, db_column='customerId', null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'change_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'change_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'change_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OriClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(blank=True, db_column='clientName', max_length=254, null=True)),
                ('regionid', models.IntegerField(blank=True, db_column='regionId', null=True)),
                ('regionsite', models.CharField(blank=True, db_column='regionSite', max_length=254, null=True)),
                ('regionphone', models.CharField(blank=True, db_column='regionPhone', max_length=254, null=True)),
            ],
            options={
                'db_table': 'ori_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OriCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityname', models.CharField(blank=True, db_column='commodityName', max_length=254, null=True)),
                ('commoditytype', models.CharField(blank=True, db_column='commodityType', max_length=255, null=True)),
                ('typeid', models.IntegerField(blank=True, db_column='typeId', null=True)),
            ],
            options={
                'db_table': 'ori_commodity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OriOrderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(blank=True, db_column='orderID', null=True)),
                ('commodityid', models.CharField(blank=True, db_column='commodityID', max_length=254, null=True)),
                ('detailprice', models.CharField(blank=True, db_column='detailPrice', max_length=254, null=True)),
                ('detailaccout', models.IntegerField(blank=True, db_column='detailAccout', null=True)),
            ],
            options={
                'db_table': 'ori_orderdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OriOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookdate', models.DateField(db_column='bookDate')),
                ('deadline', models.DateField()),
                ('total', models.FloatField()),
                ('customerid', models.PositiveIntegerField(db_column='customerId')),
            ],
            options={
                'db_table': 'ori_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OriRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionname', models.CharField(blank=True, db_column='regionName', max_length=254, null=True)),
            ],
            options={
                'db_table': 'ori_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OriType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(blank=True, db_column='typeName', max_length=254, null=True)),
                ('typestate', models.CharField(blank=True, db_column='typeState', max_length=254, null=True)),
            ],
            options={
                'db_table': 'ori_type',
                'managed': False,
            },
        ),
    ]
